### ISSUE TITLE
please add support of bitcode

### ISSUE THREAD

**Issue by denstepa** [uxcam/cordova-uxcam#3]
We got the following error while compileing app with your plugin

ld: 'Inkitt/Plugins/com.uxcam.cordova.plugin/UXCam.framework/UXCam' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can you please add support for bit code for ios 9
Thanks!

**Comment by richardgroves** [comment]
The latest releases fix this.

**Comment by GRGBISHOW** [comment]
This is still existing in version 3.2.3, any idea?

**Comment by susanuxcam** [comment]
Hey @GRGBISHOW, we tested it and everything worked smoothly on our end. Could you please share a sample app with this issue? This will help us replicate the problem!

**Comment by GRGBISHOW** [comment]
It is happening in new sample project. Just installed UXCam and added initialization in appDelegate and archived the project and got this error. It makes me to disable bitcode.

Xcode: 11.3.1
UXCam Version: 3.2.3

![Screen Shot 2020-06-12 at 17 11 28](https://user-images.githubusercontent.com/20558114/84498181-de89c500-accf-11ea-838d-f2c822ce24b0.png)

**Comment by richardgroves** [comment]
Hi @GRGBISHOW Sorry for the continued problems - can you tell me what version of XCode you are using?

**Comment by richardgroves** [comment]
Hi @GRGBISHOW 

Sorry for the continued problems. 

I suspect this is because we build the latest framework on XCode 11.5 and from the error message `'Invalid bitcode version (Producer: '1103.0.32.62.0_0' Reader: '1100.0.33.17_0')'` it looks like our Bitcode version (the producer) is higher than your XCode (the reader).

It is frustrating how Apple are changing formats and breaking compatibility so often during point releases, but we have to check on the latest iOS releases which is why we upgraded to the latest XCode quickly.

**Comment by richardgroves** [comment]
Hi @GRGBISHOW 

I can confirm that we can repeat the problem using XCode 11.3.1 - we'll do some more tests and see at what version Apple broke the bitcode format, and see if we can go back before that to build the and release and SDK update.

In the meantime are you able to update to XCode 11.5?

**Comment by richardgroves** [comment]
The table of compatibility is thus:

```

XCode version - framework vs app

FW built with: 		           11.0	      11.3   11.4	11.5

App archive with

11.0					✓	✓	X	X
11.3					✓	✓	X	X
11.4					✓	✓	✓	✓
11.5					✓	✓	✓	✓
```

The next release (2.3.4) will continue with XCode 11.5 build, but we'll review the release process to see if we can drop back to 11.3 for future releases. Either way I'll add a note to the ChangeLog to indicate required XCode version,

**Comment by GRGBISHOW** [comment]
@richardgroves Thank you for your response, I will tryout with 11.5 but support up to 11.3 in next release would be very helpful. 👍👍

**Comment by sunilmaurya04** [comment]
Hi team, I'm facing same issue for my implementation as well.
<img width="995" alt="Screenshot 2021-01-05 at 6 22 04 PM" src="https://user-images.githubusercontent.com/61402643/103648523-077ee980-4f83-11eb-8348-260a793154b3.png">
Environment:
Xcode Version: 11.6
UXCam iOS SDK version: 3.3.0

Please help us asap on this.

**Comment by richardgroves** [comment]
Hi,

It looks like Apple changed bitcode format again - can you try with XCode 12?
Due to the XCFramework and SPM (in progress) support we need to use XCode 12 to build the SDK.

Version 3.2.6 should work with XCode 11.6 if you are unable to upgrade - although we expect Apple to require XCode 12 for submissions in a few months.

**Comment by sunilmaurya04** [comment]
@richardgroves It worked with 3.2.6 version. Thanks! Please let us know once you fix the same with latest version, will update the same.

**Comment by richardgroves** [comment]
We have no plans to update newer versions to support XCode 11.6. Apple will deprecate XCode 11 for submission to app store in a couple of months so there is no benefit in continuing to support it.
